<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" 
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform" 
    xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9">
    
<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>

<xsl:template match="/">
<html>
<head>
    <title>XML Sitemap</title>
    <style type="text/css">
        body { 
            font-family: Arial, sans-serif; 
            margin: 40px; 
            background: #f5f5f5; 
            color: #333;
        }
        .container { 
            background: white; 
            padding: 40px; 
            border-radius: 8px; 
            box-shadow: 0 2px 10px rgba(0,0,0,0.1); 
            max-width: 1200px;
            margin: 0 auto;
        }
        h1 { 
            color: #666; 
            font-size: 36px; 
            margin-bottom: 10px; 
            font-weight: normal;
        }
        .intro { 
            color: #666; 
            margin-bottom: 30px; 
            line-height: 1.6; 
            font-size: 14px;
        }
        .intro a { 
            color: #007cba; 
            text-decoration: none; 
        }
        .intro a:hover { 
            text-decoration: underline; 
        }
        table { 
            width: 100%; 
            border-collapse: collapse; 
            margin-top: 20px; 
        }
        th { 
            background: #f9f9f9; 
            padding: 12px; 
            text-align: left; 
            border-bottom: 1px solid #ddd; 
            font-weight: bold; 
            color: #666; 
        }
        td { 
            padding: 12px; 
            border-bottom: 1px solid #eee; 
            vertical-align: top;
        }
        td a { 
            color: #007cba; 
            text-decoration: none; 
            word-break: break-all;
        }
        td a:hover { 
            text-decoration: underline; 
        }
        tr:hover { 
            background: #f9f9f9; 
        }
        .count { 
            margin-bottom: 20px; 
            color: #666; 
            font-size: 14px;
        }
        .iah-seo {
            color: #d63638;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>XML Sitemap</h1>
        <div class="intro">
            <p>Generated by <span class="iah-seo">IAH SEO</span>, this is an XML Sitemap, meant for consumption by search engines.</p>
            <p>You can find more information about XML sitemaps on <a href="https://sitemaps.org" target="_blank">sitemaps.org</a>.</p>
        </div>
        <div class="count">
            This XML Sitemap Index file contains <xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/> sitemaps.
        </div>
        
        <table>
            <thead>
                <tr>
                    <th>Sitemap</th>
                    <th>Last Modified</th>
                </tr>
            </thead>
            <tbody>
                <xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
                <tr>
                    <td>
                        <a href="{sitemap:loc}">
                            <xsl:value-of select="sitemap:loc"/>
                        </a>
                    </td>
                    <td>
                        <xsl:value-of select="substring(sitemap:lastmod, 1, 19)"/>
                    </td>
                </tr>
                </xsl:for-each>
            </tbody>
        </table>
    </div>
</body>
</html>
</xsl:template>

</xsl:stylesheet>